### ISSUE TITLE
Card disapears when I enable details

### ISSUE THREAD

**Issue by Mr-Groch** [mawinkler/astroweather-card#2]
Card works when `details: false`, but after I set `details: true` all card content disapears:

![Animation](https://user-images.githubusercontent.com/20594810/156140430-715d8b31-05e5-4a37-a9c0-e08936bdfd98.gif)

In dev console I can see following error:

```js
astroweather-card.js?hacstag=454670742013:227 Uncaught (in promise) ReferenceError: data_timestamp is not defined
    at AstroWeatherCard.renderDetails (astroweather-card.js?hacstag=454670742013:227:20)
    at AstroWeatherCard.render (astroweather-card.js?hacstag=454670742013:161:18)
    at AstroWeatherCard.update (styles.ts:368:1)
    at AstroWeatherCard.performUpdate (styles.ts:368:1)
    at AstroWeatherCard.scheduleUpdate (styles.ts:368:1)
    at AstroWeatherCard._$EC (styles.ts:368:1)
```

**Comment by mawinkler** [comment]
Thank you for submitting. It is already fixed in main. Will create a new release later this day.

**Comment by mawinkler** [comment]
Fixed in 0.1.4
